# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d87f245b5294511c202d5c7d4f31da39505332485057b47dacdd6cfbe7affeb9d2c072038db6a8ca36b66fefd79ddaee5402347a9aacea6651c6f992beeaf43d

test:
  secret_key_base: e4b37636684a23cd14efb2c53006c6e77216966f4f5e9f7f2030d7a3fd91f66420c3cbbf0030711baced2b2d5f5b5c090a61df833e35e633887499cb2fab5ffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
